name: golint
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
          go-version-file: ./go.mod
          cache: false
      - uses: golangci/golangci-lint-action@9d1e0624a798bb64f6c3cea93db47765312263dc
        with:
          version: latest
